Issue #23: create inference structure for nachet classification
ai-cfia/nachet-datastore pull request #25
Opened 2024-04-24 21:18 UTC by Francois-Werbrouck

References Issue #23

2024-05-28 15:56 UTC, Francois-Werbrouck commented
Based on the requierements of #23 this pr should be complete.

2024-05-28 18:58 UTC, sylvanie85 requested changes
I have an error with the new_user function, I've sent you the screenshot on teams.

2024-06-04 14:19 UTC, ChromaticPanic approved these changes

2024-06-04 16:07 UTC, sylvanie85 approved these changes

2024-06-04 16:15 UTC, merged