46 implement a structure to name and manage the picture setfolder
ai-cfia/nachet-datastore pull request #55
Opened 2024-06-26 19:55 UTC by sylvanie85

I made some fixes after i add the column name to picture_set
I also add the `get_picture_sets_info` to retrieves directories information using the db
I made some fixes and tests for azure_storage_api functions

2024-07-02 12:23 UTC, Francois-Werbrouck requested changes
I see some work in db/queries/picture, but no new tests for test_db. Other than that, nice work implementing the naming !

2024-07-02 12:23 UTC, Francois-Werbrouck commented on datastore/blob/azure_storage_api/__init__.py
> +    Returns: the names of blobs
It still is a list of the names

2024-07-02 12:23 UTC, Francois-Werbrouck commented on datastore/db/queries/picture/__init__.py
> +def new_picture_set(cursor, picture_set, user_id: str, folder_name: str = None):
I assume a picture_set still has a name on the tool even if it isn't named properly (ence why we make it optional). However I think we should still save a name if there is no name given to represent the default given name of the folder? WDYT?

2024-07-02 12:23 UTC, Francois-Werbrouck commented on datastore/blob/azure_storage_api/__init__.py
> +                "picture_set_uuid": f"{str(folder_name)}",
It doesnt sit right with me to have a tag for their uuid and the set value to their name...
```suggestion
                "picture_set_uuid": f"{str(folder_uuid)}",
```

2024-07-02 17:47 UTC, Francois-Werbrouck approved these changes
LGTM! Nice work on the trigger!

2024-07-02 17:47 UTC, Francois-Werbrouck commented on datastore/db/bytebase/trigger_insert_picture_set_default_name.sql
Great this fixes: 

> I assume a picture_set still has a name on the tool even if it isn't named properly (ence why we make it optional). However I think we should still save a name if there is no name given to represent the default given name of the folder? WDYT?

2024-07-02 21:03 UTC, ChromaticPanic commented on datastore/blob/azure_storage_api/__init__.py
>                      count += 1
How does this work with the different image formats? jpg, tif, tiff . do we save them all as png?

2024-07-02 21:03 UTC, ChromaticPanic commented on datastore/blob/azure_storage_api/__init__.py
>                  "picture_set_uuid": f"{str(folder_uuid)}",
How does this work with the different image formats? jpg, tif, tiff . do we save them all as png?

2024-07-03 15:06 UTC, ChromaticPanic approved these changes

2024-07-03 15:08 UTC, merged